# markdown: kramdown
# markdown: rdiscount
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
permalink: /:year/:month/:title/
url: http://emx2.co.uk/cn
author: 孟新
pygments: true

